### ISSUE TITLE
v3.0.19 fails to build with libressl

### ISSUE THREAD

**Issue by Zirias** [FreeRADIUS/freeradius-server#2611]
FreeRADIUS 3.0.19 doesn't build with libressl 2.8.3 any more, it shows the following build warnings:

    src/main/tls.c:3286:33: warning: incompatible pointer types passing 'SSL_SESSION 
     *(SSL *, unsigned char *, int, int *)' (aka 'struct ssl_session_st *(struct ssl_st *, unsigned char *, int, int *)') to parameter of type 'SSL_SESSION *(*)(struct ssl_st *, const unsigned char *, int, int *)' (aka 'struct ssl_session_st *(*)(struct ssl_st *, const unsigned char *, int, int *)') [-Wincompatible-pointer-types]
                            SSL_CTX_sess_set_get_cb(ctx, cbtls_get_session);
                                                         ^~~~~~~~~~~~~~~~~         
    /usr/local/include/openssl/ssl.h:730:20: note: passing argument to parameter 'get_session_cb' here
        SSL_SESSION *(*get_session_cb)(struct ssl_st *ssl,
                       ^
    src/main/tls.c:3383:3: warning: implicit declaration of function 'SSL_CTX_set_num_tickets' is invalid in C99 [-Wimplicit-function-declaration]
                    SSL_CTX_set_num_tickets(ctx, 1);
                    ^
    src/main/tls.c:3396:3: warning: implicit declaration of function 'SSL_CTX_set_num_tickets' is invalid in C99 [-Wimplicit-function-declaration]
                    SSL_CTX_set_num_tickets(ctx, 0);
                    ^

This leads to this linker error:

    LINK build/bin/radiusd
    /usr/bin/ld: error: undefined symbol: SSL_CTX_set_num_tickets
    >>> referenced by tls.c
    >>>               build/objs/src/main/tls.o:(tls_init_ctx)

See also [FreeBSD Bug 237216](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237216)

The following simple patch fixes the build:

    --- src/main/tls.c.orig        2019-04-12 06:47:56 UTC
    +++ src/main/tls.c
    @@ -1579,7 +1579,7 @@ done:
           return 0;
     }
     
    -#if OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)
    +#if OPENSSL_VERSION_NUMBER < 0x10100000L
     static SSL_SESSION *cbtls_get_session(SSL *ssl, unsigned char *data, int len, int *copy)
     #else
     static SSL_SESSION *cbtls_get_session(SSL *ssl, const unsigned char *data, int len, int *copy)
    @@ -3379,14 +3379,14 @@ post_ca:
                    */
                   SSL_CTX_sess_set_cache_size(ctx, conf->session_cache_size);
     
    -#if OPENSSL_VERSION_NUMBER >= 0x10101000L
    +#if OPENSSL_VERSION_NUMBER >= 0x10101000L && !defined(LIBRESSL_VERSION_NUMBER)
                   SSL_CTX_set_num_tickets(ctx, 1);
     #endif
     
           } else {
                   SSL_CTX_set_session_cache_mode(ctx, SSL_SESS_CACHE_OFF);
     
    -#if OPENSSL_VERSION_NUMBER >= 0x10101000L
    +#if OPENSSL_VERSION_NUMBER >= 0x10101000L && !defined(LIBRESSL_VERSION_NUMBER)
                   /*
                    *      This controls the number of stateful or stateless tickets
                    *      generated with TLS 1.3.  In OpenSSL 1.1.1 it's also

**Comment by arr2036** [comment]
Please submit patches that specify specific libressl version numbers. libressl 2.9.0 appears to add API compatibility with OpenSSL 1.1.0 so just checking for the presence or absence of LIBRESSL_VERSION_NUMBER is not an accurate method of determining what functionality libressl supports.

**Comment by Zirias** [comment]
It isn't that simple. The two checks I added are about OpenSSL 1.1.1, there is no libressl version yet that's compatible with that. So there's no way to do these checks for specific version numbers.

Leaves me with the one I removed; this could indeed be replaced with a specific version -- I assume libressl did that API change in version 2.8.0, but I'm not sure about it.

**Comment by arr2036** [comment]
Then add a note against the preprocessor checks stating that OpenSSL 1.1.1 wasn't supported as of version 2.9.0.  Be advised if you want to keep these checks in v3.0.x, you should also do the same for the existing uses of LIBRESSL_VERSION_NUMBER, otherwise, libressl support in v3.0.x will go the way it just did in master branch (9652affe38f41ba2484e013cf9d2c0bcb8c80d67).

**Comment by Zirias** [comment]
So you took this issue as an opportunity for dropping libressl support? IMHO, using libressl version numbers isn't going to work out well, because libressl follows the OpenSSL API and defines the OPENSSL_VERSION_NUMBER macros accordingly -- incompatibilities still happen, and there might be OpenSSL API changes that aren't supported by libressl at all yet (as those for 1.1.1). What's typically done is adding just a few checks for LIBRESSL_VERSION_NUMBER being defined, so the *current stable* version of libressl is supported. This is normally enough for anyone building from source and for projects like OpenBSD or void linux that use libressl as system-wide replacement.

But of course, if you decide to drop libressl support, this renders this issue invalid.

**Comment by arr2036** [comment]
I don't see your point.  The current stable version of libressl is not fixed, it's going to change, and when it does, we will need to re-evaluate which APIs we use when linked with libressl. Without version numbers and comments we have absolutely no idea against which version of libressl this evaluation was last performed against, and no idea when we can strip out old compatibility code. 

It's not that we don't want to support libressl, it's that we resent the poor quality of patches which have been submitted so far to support it.  Or, to be more explicit, continuing to support Theo de Raadt's little ego trip is fine, but it should not come at the expense of additional effort for our development team.

**Comment by alandekok** [comment]
> So you took this issue as an opportunity for dropping libressl support? 

Don't be an asshole.

This is open source software.  You're welcome to contribute.  If you're too lazy to contribute a decent patch, then don't complain that we're too lazy to jump to your every whim.

**Comment by Zirias** [comment]
> > So you took this issue as an opportunity for dropping libressl support?

> Don't be an asshole.

So *isn't* this exactly what happened? The instance I posted this issue, all checks for libressl were removed from master. Not much to interpret here.

Yes, this is opensource, and I don't *expect* you to support libressl. But if you do, supporting the latest stable version by introducing just a few checks where those for `OPENSSL_VERSION_NUMBER` aren't enough (although they should, as libressl is defining them) is the one sane thing to do, and it looks like you did in the past. If you feel this is too convoluted and/or requires too many changes, that's fine. But trying to determine exact version ranges where libressl claimed openssl x.y.z API support while getting feature "foo" wrong -- I guess you don't want to do this, and I don't want that either, for obvious reasons.

**Comment by arr2036** [comment]
The commit message in master explicitly said, we would support libressl in master, if someone were to post decent patches that specified the libressl version numbers.

**Comment by alandekok** [comment]
> So isn't this exactly what happened? The instance I posted this issue, all checks for libressl were removed from master. Not much to interpret here.

Yes, this is *exactly* what happened.  You filed an issue about the v3.0.x branch.  Then when we made changes to a *different* branch, you got confused, and complained.

I agree that there's nothing to interpret here.  Your comments about the "master" branch were unreasonable and inappropriate.  Hence my "don't be an asshole" comment.

If you don't want to be called out for bad behavior, don't engage in bad behavior.

We try to support libressl on the v3.0.x branch.  But if it's too much work, we'll drop it.  We don't owe you anything.

**Comment by Zirias** [comment]
Oh, now we have *confused* **and** *asshole*. And you're probably trying to tell me the exact time of the commit to master is just coincidence. Well, I won't bother you any further with unwanted patches.

**Comment by alandekok** [comment]
> And you're probably trying to tell me the exact time of the commit to master is just coincidence. 

Of course it's not a coincidence.  The problem here is you wanting to get v3.0.x working (which is fine), but then bitching about a different branch, after not reading the "master" commit message.

>  Well, I won't bother you any further with unwanted patches.

See?  You're an asshole.  We're happy to accept patches, as you well know.  So this comment is just you doubling down on lies and poor behavior.
