### ISSUE TITLE
Resolving DNS name to SAN IP Address

### ISSUE THREAD

**Issue by mark-grayson** [FreeRADIUS/freeradius-server#2841]
# Issue type
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
In FreeRADIUS, version 3.0.18, with an FQDN defined as the Common Name in a Client Certificate, with an IP Address attribute in the Subject Alternative Name of a Client Certificate, no SAN IP Address OID is expanded and no DNS confirmation of the IP Address may be performed.  Certificates should be able to be verified against their SAN IP Address of the Common Name.

## Background
This issue is being raised on behalf of Wireless Broadband Alliance.
WBA is currently evolving its WRIX RADIUS Roaming system to enable support of RADSEC.
RADSEC testing has been performed by multiple WBA members, including:
Accuris Networks, BSG Wireless, Cablelabs, Cisco and iPass/Pareteum

**Comment by arr2036** [comment]
This can likely be done in policy using the rlm_unbound module if v3.0.x allows breakout into a virtual server for client certification validation.  It's been so long since I worked on v3.0.x, I can't remember if that functionality is available.  Maybe @alandekok can comment.

**Comment by arr2036** [comment]
Apparently the certificate attributes are available in the main virtual server as you state in #2840, in which case it's up to you to define policies to validate the incoming client certificates and their contents.

It's highly unlikely that we'd change the v3.0.x series to perform DNS validation by default as the architecture is fully blocking, and an unresponsive DNS server would cause the FreeRADIUS worker threads to block making the server appear unresponsive.

As I stated in my previous comment, you can use rlm_unbound and its string expansions to perform the validation you describe, but in a production environment it's probably a bad idea, as the rlm_unbound expansions are also blocking.

Depending on how much of a priority this is, the WBA could sponsor the reimplementation of RADSEC in the FreeRADIUS master branch and the conversion of rlm_unbound to async I/O, or you could use radsecproxy as a frontend and attempt the validation there.

**Comment by alandekok** [comment]
>  no SAN IP Address OID is expanded 

It's not clear what that means.  If the OID is there, it's turned into an attribute.

Do you have debug output showing the problem?

But as Arran said, it's difficult to add DNS checks to v3.  You could check `Packet-Src-IP-Address` against an IP address in the OID.  That would ensure that the connection is coming from the correct IP.

And to be honest, cross-checking DNS names in the client certificate against originating IP addresses is a low priority.  If the connection has a valid client certificate, it matters a lot less where the connection is coming from.  Client certificates should be kept secure, and not shared across multiple systems.

It would help if we could get access to the proposed standards.  As authors of the leading RADIUS server, it would be beneficial to everyone if we were permitted to participate.  But as an Open Source project, we just can't afford 10K+ per year.

Other standards bodies (Trusted Computing Group) have the option to include outsiders as designated experts.  Perhaps something similar could be done here.
