### ISSUE TITLE
rlm_krb5: Corner case Heimdal vs. MIT

### ISSUE THREAD

**Issue by matsimon** [FreeRADIUS/freeradius-server#1466]
I've discovered likely a corner case on FreeBSD that is due to the change of the options to configure rlm_krb5 as introduced with 3.0.1 in 7889d4b840920526b4598422771617d389ea5ab7: 

__--with-rlm-krb5-dir__ replaced both __--with-rlm-krb5-include-dir__ and __--with-rlm-krb5-lib-dir__.

On FreeBSD a version of Heimdal is in the base system, however the operator is free to install a newer Heimdal or MIT kerberos from ports to (typically) /usr/local

rlm_krb5 is properly built and linked against MIT or Heimdal from ports when __--with-rlm-krb5-dir=/usr/local__ is given. It also works to link against Heimdal in the base system when Heimdal from ports is installed. (I've subsequently checked against what rlm_krb5.so is linked to be sure)

However the configure script for rlm_krb5 must get confused when I'd like to link against Heimdal in base (__--with-rlm-krb5-dir=/__) but for whatever reason... MIT kerberos from ports is installed.

I guess that it sees both since we have to provide __/__ in order to find the heimdal in the base system.
With the previous switches this could have been avoided I guess.

I guess that is likely to happen on other systems where different Kerberos versions can be installed (i.e. when using something like pkgsrc, macports or another external packaging system).

What is best to provide to get a better insight?

**Comment by matsimon** [comment]
Here is the end of make when it stops:
As reminder, it does work on 10.2 when MIT is absent and configure is set to build against heimdal in base, so it's only if MIT is installed from packages and freeradius should be linked against heimdal in base.

```
CC src/modules/rlm_exec/rlm_exec.c
In file included from src/modules/rlm_krb5/rlm_krb5.c:32:
src/modules/rlm_krb5/krb5.h:41:2: error: unknown type name 'krb5_verify_opt'
        krb5_verify_opt options;
        ^
src/modules/rlm_krb5/rlm_krb5.c:347:8: warning: implicit declaration of function 'krb5_verify_user_opt' is invalid in C99 [-Wimplicit-function-declaration]
        ret = krb5_verify_user_opt(conn->context, client, request->password->vp_strvalue, &conn->options);
              ^
1 warning and 1 error generated.
scripts/boiler.mk:630: recipe for target 'build/objs/src/modules/rlm_krb5/rlm_krb5.lo' failed
gmake[2]: *** [build/objs/src/modules/rlm_krb5/rlm_krb5.lo] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from src/modules/rlm_krb5/krb5.c:28:
src/modules/rlm_krb5/krb5.h:41:2: error: unknown type name 'krb5_verify_opt'
        krb5_verify_opt options;
        ^
src/modules/rlm_krb5/krb5.c:151:2: warning: implicit declaration of function 'krb5_verify_opt_init' is invalid in C99 [-Wimplicit-function-declaration]
        krb5_verify_opt_init(&conn->options);
        ^
src/modules/rlm_krb5/krb5.c:152:2: warning: implicit declaration of function 'krb5_verify_opt_set_ccache' is invalid in C99 [-Wimplicit-function-declaration]
        krb5_verify_opt_set_ccache(&conn->options, conn->ccache);
        ^
src/modules/rlm_krb5/krb5.c:154:2: warning: implicit declaration of function 'krb5_verify_opt_set_keytab' is invalid in C99 [-Wimplicit-function-declaration]
        krb5_verify_opt_set_keytab(&conn->options, conn->keytab);
        ^
src/modules/rlm_krb5/krb5.c:155:2: warning: implicit declaration of function 'krb5_verify_opt_set_secure' is invalid in C99 [-Wimplicit-function-declaration]
        krb5_verify_opt_set_secure(&conn->options, true);
        ^
src/modules/rlm_krb5/krb5.c:157:21: warning: implicit declaration of function 'krb5_verify_opt_set_service' is invalid in C99 [-Wimplicit-function-declaration]
        if (inst->service) krb5_verify_opt_set_service(&conn->options, inst->service);
                           ^
5 warnings and 1 error generated.
scripts/boiler.mk:630: recipe for target 'build/objs/src/modules/rlm_krb5/krb5.lo' failed
gmake[2]: *** [build/objs/src/modules/rlm_krb5/krb5.lo] Error 1
gmake[2]: Leaving directory '/usr/ports/net/freeradius3/work/freeradius-server-3.0.10'
===> Compilation failed unexpectedly.
````

**Comment by alandekok** [comment]
Having two incompatible libraries on the same system is, in general, a bad idea.  Asking the compiler / linker to use one library is easy.  Asking them to *ignore* the other is much more difficult.

Honestly, I don't think there's an easy solution.  You can install *both* libraries in non-standard places, and then tell the build system about only one.  However, if one of them is installed in the standard include / lib path, it is pretty much impossible.  This is because you want the build system to find standard headers / libraries in the standard path... *except* for one header / library.

It gets worse when you install both libraries in sandard places where the compiler / linker finds them by default.  At that point, it's impossible to say "use everything in /usr/include *except* for foo.h, but also find a different implementation of the same thing in /usr/include/bar.h".

The short answer is "don't install multiple or competing versions of the same libraries".

**Comment by matsimon** [comment]
Hi Alan

Thanks for your answer, in short: I'll have to ask how FreeBSD folks think about this and think about where and possibly how the issue could be adressed properly.

Fact is that in FreeBSD base system and and packages/ports are separate and thus ports don't necessarily link against what is in base - actually that's why all things are configured and built to a $LOCALBASE which by default is __/usr/local__. It's like using OS X with Macports which in this case their case tries to to completely avoid any dependency on libraries of the main OS and encapsulates everything on __/opt/local__. (Apple also ships a Kerberos in the OS but that one is derived from MIT as it seems, but again it's not native MIT kerberos)

Previously / currently (which is broken thus I found about) the port makefile for sets the following for Heimdal in base:
````
CONFIGURE_ARGS+=--with-rlm-krb5-lib-dir=/usr/lib
CONFIGURE_ARGS+=--with-rlm-krb5-include-dir=/usr/include
````

And for a Heimdal or MIT from the ports collection:
````
CONFIGURE_ARGS+=--with-rlm-krb5-lib-dir=${LOCALBASE}/lib
CONFIGURE_ARGS+=--with-rlm-krb5-include-dir=${LOCALBASE}/include
````
This made certain the right library was detected and used. With the new option we can only set / or /usr/local and that's what confuses it.

I guess I should think about where the issues would be best handled properly. If in the port definition of FreeBSD by means of a patch or on the FreeRADIUS side.

-- Mathieu

**Comment by arr2036** [comment]
Shouldn't it be ``--with-rlm-krb5-dir=/usr/``  there is no ``/include`` or ``/lib`` on most systems?

Specifying the lib dir and include dir for kerberos is wrong.  Both kerberos distributions ship with a utility which provides all the required CFLAGS and LDFLAGS to link and build against the correct version of kerberos.  Not using that utility, and specifying the flags manually is a great way to end up with the rlm_krb5 misidentifying the kerberos flavour its building against, and introducing weird linker issues.

**Comment by arr2036** [comment]
It's linking against MIT, because you specified the base path wrong, so it doesn't pick up the krb5-config in /usr/bin, and instead picks up the MIT one from /usr/local/bin.

**Comment by matsimon** [comment]
Arran, OK I'll take a look into this, yes there is no /include on FreeBSD too.

The current port on FreeBSD links always against Heimdal so that's a bug. That's why I try to come up with a fix and after doing some source code archeology I found the mentioned commit that replaced the 2 previous switch by this current one and tried to figure its proper use.

-- Mathieu

**Comment by matsimon** [comment]
I mentioned the issue FreeBSD's Bugzilla as [PR 205493](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205493). I'll leave the decision to you if you want to keep this bug open.

I'm more than willing to pass an eventual upstream fix once the FreeBSD port maintainer has decided what he'd prefer.

**Comment by arr2036** [comment]
Will close for now.  Let us know when there's a response from the port maintainer.
