### ISSUE TITLE
Freeradius 3.0.10 not compiling on Solaris

### ISSUE THREAD

**Issue by sandereerd** [FreeRADIUS/freeradius-server#1366]
Hello,

I had some issues on compiling Freeradius 3.0.10 on Solaris 11.
The issue seems to be that Soalris does not follow the POSIX standard (as always), and as such does not have the vdprintf function. https://www.gnu.org/software/gnulib/manual/html_node/vdprintf.html

The use of this function in freeradius was introduced in commit 9739749ad0b75816c458fde0c6af420e87c89c1b
I can get it to compile by replacing line 1043 in src/lib/debug.c again to use the vfprintf in stead of vdprintf. Is this the way to go, or how is this issue best fixed so we can keep Freeradius up and running on our solaris boxes in the future?

I would gladly try compiling again in my environment if this helps.
Please let me know if you need more info, snippets of the failed compile can be found below.

Kind regards
Sander Eerdekens

And Ps: Great work on V3, been using it in play environement for a while and has been steady as a rock!

===

sippet of the gmake command:

====
CC jlibtool.c
CC src/lib/cbuff.c
CC src/lib/cursor.c
CC src/lib/debug.c
src/lib/debug.c: In function âfr_fault_logâ:
src/lib/debug.c:1055:2: warning: implicit declaration of function âvdprintfâ [-Wimplicit-function-declaration]
  vdprintf(fr_fault_log_fd, msg, ap);
  ^
src/lib/debug.c:1055:2: warning: nested extern declaration of âvdprintfâ [-Wnested-externs]
CC src/lib/dict.c
CC src/lib/filters.c
.....
....
CC src/main/pair.c
CC src/main/xlat.c
Undefined                       first referenced
 symbol                             in file
vdprintf                            build/lib/local/.libs/libfreeradius-radius.so
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
gmake: *** [build/bin/local/radeapclient] Error 1

=====

**Comment by arr2036** [comment]
Hmm, no.  As of v3.1.x we require POSIX-2008 support which includes that function, so for future compatibility it's better to add a copy of vdprintf to missing.c.

**Comment by sandereerd** [comment]
Thank you for the feedback!
So far I've not been able to get it working with the missing.c, as vdprintf has other dependencies, with a whole cascade of other dependencies which are missing.
My efforts with gnulib have been unsuccessful so far :)

I'll try to pick this up with oracle, to see what they recommend

**Comment by arr2036** [comment]
Shouldn't have the most, you just need to get a FILE * from the FD and use vfprintf right? Or are the functions not there to do that?  We're not looking for it to be amazingly efficient, just to work.

**Comment by sandereerd** [comment]
Thanks for the pointers!
I was able to get things compiling by adding this to src/lib/missing.c

int vdprintf (int fd, const char *format, va_list args)
{
	FILE* fp = fdopen(fd, "w");
	return vfprintf(fp,format,args);
}

If I don't want warnings during compiling, I need to add this line to src/include/missing-h as well:

int vdprintf (int fd, const char *format, va_list args);


Can this just be added into the code, or should extra checks be added to the configure step?
In both cases, can you or one of the other developers pick this up to include it? I have far to little programming skills to write something useful :)

**Comment by arr2036** [comment]
Should be:

```c
int vdprintf (int fd, const char format, va_list args)
{
	int		ret;
	FILE	*fp;

 	fp = fdopen(fd, "w");
	if (!fp) return -1;

	ret = vfprintf(fp, format, args);
	fclose(fp);
	return ret;	
}
```

Else you probably leak FILLE *'s :)

I'll add the various checks, good to know this is all that's needed.

**Comment by jpereira** [comment]
@arr2036 I think that this doesn't works.

e.g:

```C
int ret;
va_list ap;
int fd = open ("/path/file", .......);
.....
ret = vdprintf(fd, fmt, ap); // this will be returned with -1, because will catch a problem during fdopen()
```

**Comment by jpereira** [comment]
My suggestion is:

```C
int vdprintf(int d, const char *format, va_list ap)
{
	char buf[BUF_SIZE];
	int len;

	len = vsnprintf(buf, BUF_SIZE, format, ap);
	return write(d, buf, len);
}
```

this is correct.

**Comment by arr2036** [comment]
Ok... but what are the cases where fdopen will fail?

**Comment by arr2036** [comment]
```text
     [EINVAL]           The mode argument to fopen(), fdopen(), or freopen() was invalid.
```

Probably not going to fail...

**Comment by arr2036** [comment]
So it comes down to which is faster, vasprintf and free or fdopen and vfprintf.  Given the way vasprintf has to calculate the length of the alloced string first, and malloc the memory before writing anything, it's probably going to be fdopen and fclose.  I don't know, and honestly I don't really care that much.

The function only gets called by the debug logger, and optimizing performance for Solaris is absolutely not a priority.

**Comment by arr2036** [comment]
We shouldn't even be entertaining adding this function, except it's quite a minor change.  We only support POSIX-2008 compliant systems in v3.1.x.  If Solaris doesn't implement this function it's not POSIX-2008 compliant.
