### ISSUE TITLE
Undefined reference errors in tls.c during compilation

### ISSUE THREAD

**Issue by tdebaets** [FreeRADIUS/freeradius-server#1572]
When I try to compile branch 3.0.x on CentOS 5, the compilation fails with these linker errors:

```
build/objs/src/main/tls.o: In function `tls_application_data':
/root/freeradius-server-3.0.x/src/main/tls.c:3295: undefined reference to `tls_error_io_log'
build/objs/src/main/tls.o: In function `tls_init_ctx':
/root/freeradius-server-3.0.x/src/main/tls.c:2654: undefined reference to `tls_error_log'
/root/freeradius-server-3.0.x/src/main/tls.c:2672: undefined reference to `tls_error_log'
/root/freeradius-server-3.0.x/src/main/tls.c:2839: undefined reference to `tls_error_log'
/root/freeradius-server-3.0.x/src/main/tls.c:2849: undefined reference to `tls_error_log'
/root/freeradius-server-3.0.x/src/main/tls.c:2663: undefined reference to `tls_error_log'
build/objs/src/main/tls.o:/root/freeradius-server-3.0.x/src/main/tls.c:2488: more undefined references to `tls_error_log' follow
build/objs/src/main/tls.o: In function `tls_handshake_send':
/root/freeradius-server-3.0.x/src/main/tls.c:760: undefined reference to `tls_error_io_log'
build/objs/src/main/tls.o: In function `tls_handshake_recv':
/root/freeradius-server-3.0.x/src/main/tls.c:681: undefined reference to `tls_error_io_log'
/root/freeradius-server-3.0.x/src/main/tls.c:716: undefined reference to `tls_error_log'
build/objs/src/main/tls.o: In function `tls_new_session':
/root/freeradius-server-3.0.x/src/main/tls.c:557: undefined reference to `tls_error_log'
build/objs/src/main/tls.o: In function `tls_new_client_session':
/root/freeradius-server-3.0.x/src/main/tls.c:506: undefined reference to `tls_error_io_log'
collect2: ld returned 1 exit status
make: *** [build/bin/local/radeapclient] Error 1
```

I have no clue why the linker is unable to find the tls_error_log and tls_error_io_log functions, as these are just defined in the same tls.c file. This was probably introduced by commit 8d8234b. Could someone have a look? Thanks!

**Comment by alandekok** [comment]
You probably need to re-run "configure".

**Comment by tdebaets** [comment]
Unfortunately that didn't help. I get the same errors after a new run of `./configure`. Any other ideas?

**Comment by alandekok** [comment]
Hmm.. CentOS 5 is at least 6 years old, and the base distribution is 10 years old.  This kind of bug isn't a high priority.

It's better to use a recent distribution than for us to track down why valid C code doesn't compile.

**Comment by tdebaets** [comment]
Ok, but the latest 3.0.11 release still compiles and works fine on CentOS 5. I can understand that I can't use 3.1, but shouldn't 3.0 continue to work for the sake of backwards compatibility?

**Comment by arr2036** [comment]
You have done

```
rm -rf build
make
```

right?

**Comment by tdebaets** [comment]
I have just tried it and it doesn't make any difference. `make clean` doesn't help either.

**Comment by alandekok** [comment]
We don't have CentOS 5 here, and aren't inclined to install it just to fix a bug.  CentOS is 10 years old, and the base RedHat OS isn't even supported by RedHat any more.

The code seems to be correct, and builds for all Linux / BSD distributions we have access to.  So our inclination is to say it's a CentOS 5 bug, and to ignore it.

The larger question is why are you running such an old distribution?  It costs nothing to install a recent version of CentOS, which will work.

**Comment by lytboris** [comment]
My FreeBSD build is failed too. Actually, this seems to be a failure for radeapclient rather than tls.o itself:

`build/make/jlibtool --silent --mode=link gcc -o build/bin/local/radeapclient -rpath /usr/home/lytboris/git/freeradius-server/build/lib/local//.libs  -L/usr/local/lib -Wl,-rpath,/usr/local/lib    build/objs//home/lytboris/git/freeradius-server/src/modules/rlm_eap/radeapclient.lo build/objs//home/lytboris/git/freeradius-server/src/main/files.lo build/objs//home/lytboris/git/freeradius-server/src/main/threads.lo build/objs//home/lytboris/git/freeradius-server/src/main/version.lo build/objs//home/lytboris/git/freeradius-server/src/main/cb.lo build/objs//home/lytboris/git/freeradius-server/src/main/tls.lo build/lib/local/libfreeradius-radius.la build/lib/local/libfreeradius-server.la build/lib/local/libfreeradius-eap.la  -lcrypto -lssl -ltalloc  -lpcre -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lexecinfo -lpthread  -lreadline -lcrypto -lssl

build/objs//home/lytboris/git/freeradius-server/src/main/tls.o: In function `tls_new_client_session':
/home/lytboris/git/freeradius-server/src/main/tls.c:506: undefined reference to `tls_error_io_log'
build/objs//home/lytboris/git/freeradius-server/src/main/tls.o: In function `tls_new_session':
`

**Comment by mcnewton** [comment]
Just successfully built a clean v3.0.x HEAD on fresh install of FreeBSD 9.3-RELEASE. No problems at all, including radeapclient.

**Comment by lytboris** [comment]
Yeah, I know, I have another RELENG_10 machine with no issues. Will dig it tomorrow properly and update this thread with findings.

**Comment by lytboris** [comment]
It is arr2036's 8d8234be306db76b16550fbca443818c7d2f9fed commit that breaks build. Previous 296eeeb103cac714a58ae64a8130664b527495eb is OK.

**Comment by lytboris** [comment]
Here you go
https://github.com/FreeRADIUS/freeradius-server/pull/1586

**Comment by tdebaets** [comment]
Compilation on CentOS 5 is now again fine as well, thanks!
