### ISSUE TITLE
freeradius.server does not compile with talloc-2.1.13 installed

### ISSUE THREAD

**Issue by buczek** [FreeRADIUS/freeradius-server#2258]
freeradius-server fails to compile when talloc-2.1.13 is installed, because `talloc_set_memlimit` is no longer exported in that version. fe4ab18f6dcb8b0d0b7bb07846ca7582a7e018d8 already added a check for `talloc_set_memlimit` to `configure.ac`, because, as the comment says, "This was only included in version 2.0.8". However, the source files call it unconditionally and don't use `HAVE_TALLOC_SET_MEMLIMIT`.

```
buczek@theinternet:/dev/shm/freeradius-server (master)$ ./configure --prefix=/dev/shm/freeradius-test
checking build version... 040000
checking build version string... 4.0.0
checking for git... yes
checking build release... 14868
checking build commit... 2da8dcc57
configure: in git repository, enabling developer build implicitly, disable with --disable-developer
[...]
checking for talloc_set_memlimit... no
checking for talloc_pooled_object... no
[...]
config.status: creating all.mk
config.status: creating config.h
buczek@theinternet:/dev/shm/freeradius-server (master)$ make -j $(nproc)
CC jlibtool.c
HEADER src/include/attributes.h
HEADER src/include/features.h
HEADER src/include/rfc4675.h
HEADER src/include/rfc2869.h
[...]
LINK build/lib/libfreeradius-eap-sim.la
LINK build/bin/radwho
build/lib/local/.libs/libfreeradius-server.so: undefined reference to `talloc_set_memlimit'
collect2: error: ld returned 1 exit status
make: *** [scripts/boiler.mk;647: build/bin/local/radwho] Error 1
make: *** Waiting for unfinished jobs....
build/lib/local/.libs/libfreeradius-server.so: undefined reference to `talloc_set_memlimit'
collect2: error: ld returned 1 exit status
make: *** [scripts/boiler.mk;647: build/bin/local/radmin] Error 1
build/lib/local/.libs/libfreeradius-server.so: undefined reference to `talloc_set_memlimit'
collect2: error: ld returned 1 exit status
make: *** [scripts/boiler.mk;647: build/bin/local/unit_test_attribute] Error 1
build/lib/local/.libs/libfreeradius-server.so: undefined reference to `talloc_set_memlimit'
collect2: error: ld returned 1 exit status
make: *** [scripts/boiler.mk;647: build/bin/local/unit_test_map] Error 1
build/lib/.libs/libfreeradius-server.so: undefined reference to `talloc_set_memlimit'
collect2: error: ld returned 1 exit status
make: *** [scripts/boiler.mk;648: build/bin/radmin] Error 1
build/lib/.libs/libfreeradius-server.so: undefined reference to `talloc_set_memlimit'
collect2: error: ld returned 1 exit status
make: *** [scripts/boiler.mk;648: build/bin/radwho] Error 1
buczek@theinternet:/dev/shm/freeradius-server (master)$
```
